export const BG_IMG = "https://assets.nflxext.com/ffe/siteui/vlv3/594f8025-139a-4a35-b58d-4ecf8fdc507c/d3c4e455-f0bf-4003-b7cd-511dda6da82a/IN-en-20240108-popsignuptwoweeks-perspective_alpha_website_small.jpg"
export const LOGO = "https://res.cloudinary.com/dhqgc5kzm/image/upload/v1705491730/netflix-logo_wss2p8.png"
export const USER_AVATAR = "https://occ-0-2186-2164.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABXz4LMjJFidX8MxhZ6qro8PBTjmHbxlaLAbk45W1DXbKsAIOwyHQPiMAuUnF1G24CLi7InJHK4Ge4jkXul1xIW49Dr5S7fc.png?r=e6e"
export const API_KEY = "b8a611ec3c3d2c69b1473cc2160f6c73"
export const API_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiOGE2MTFlYzNjM2QyYzY5YjE0NzNjYzIxNjBmNmM3MyIsInN1YiI6IjYxYzQwYjY2YTkzZDI1MDA0MTNiZmYzZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.DRyxWu31gciKYBG-ekWy-rvBbfSow5Z2LhhdPFjpALw"
export const NOW_PLAYING_MOVIES_URL = "https://api.themoviedb.org/3/movie/now_playing?page=1"
export const POPULAR_MOVIES_URL = "https://api.themoviedb.org/3/movie/popular?page=1"
export const UPCOMING_MOVIES_URL = "https://api.themoviedb.org/3/movie/upcoming?page=1"
export const TOP_RATED_MOVIES_URL = "https://api.themoviedb.org/3/movie/top_rated?page=1"
export const VIDEO_BASE_URL = "https://api.themoviedb.org/3/movie"
export const POSTER_BASE_URL = "https://image.tmdb.org/t/p/w500"
export const SUPPORTED_LANGUAGES = [{ identifier: "en", name: "English" }, { identifier: "hindi", name: "Hindi" }, { identifier: "spanish", name: "Spanish" }]